# Config file for Telegram Captcha Bot

cas_enable = "yes"

captcha = "Captcha: %s"

captcha_enable = "Greeting with captcha for new users activated."

attack_mode = "Attack mode status: %s"

attack_mode_enable = "In attack mode, all new participants receive a 5-minute ban. The welcome message is not displayed. To deactivate, repeat the /attack command"

# Button text
button_text = "I'm not a robot!"

ban_button_text = "I'm robot!."

# Bot sends this message to new users
welcome_message = "Hello! This is the spam protection system. Please press the button within 30 seconds or you will be banned!"

# Edit welcome message with this text if user passed validation
after_success_message = "User passed the validation."

# Edit welcome message with this text if user failed validation
after_fail_message = "User didn't pass the validation and was banned."

# Show success and failure messages or delete them. Pick "show" or "del"
print_success_and_fail_messages_strategy = "del"

# During this time in seconds, the new user have to press the captha button
welcome_timeout = "30"

# If the new user does not press the button, the bot will ban the user for this duration of time. Can be "forever" or number of minutes ("10")
ban_duration = "10"

fake_ban_duration_min = "60"

# Do you want to use a socks5 proxy server? Can be "yes" or "no"
use_socks5_proxy = "no"

# Socks5 proxy server IP address
socks5_address = "1.1.1.1"

# Socks5 proxy server TCP port
socks5_port = "1080"

# Socks5 proxy server username
socks5_login = "login"

# Socks5 proxy server password
socks5_password = "password"
